import { 
  UserNeighbor, 
  Post, 
  ServiceSwap, 
  MarketplaceItem, 
  EcoWastePoint, 
  EcoWasteReport, 
  CommunityEvent, 
  DirectMessage, 
  ReputationVouch,
  UserStory,
  FacebookReel,
  CommunityGroup,
  FacebookPage,
  FriendRequest,
  FacebookNotification,
  ProfessionalMetrics
} from './types';

// Official Founders of Cacuso Online as requested
export const FOUNDERS: UserNeighbor[] = [
  {
    id: 'founder-jelson',
    name: 'Jelson Pereira Manuel',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80',
    neighborhood: 'Bairro Central, Cacuso',
    reputationScore: 99,
    vouchesCount: 142,
    badges: ['Criador Oficial', 'Inovador Social', 'Guardião Comunitário', 'Nó de Validação'],
    isFounder: true,
    roleTitle: 'Co-Fundador & Arquiteto de Inovação Social',
    keyFingerprint: '4A9F:882C:E310:7B99:99F1:D0A4',
    completedExchanges: 48,
    ecoMeritPoints: 920,
    joinedDate: 'Fevereiro 2025',
  },
  {
    id: 'founder-liron',
    name: 'Liron Kilson',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&auto=format&fit=crop&q=80',
    neighborhood: 'Bairro Central, Cacuso',
    reputationScore: 99,
    vouchesCount: 138,
    badges: ['Criador Oficial', 'Criptografia & Privacidade', 'Defensor Ecológico', 'Nó de Validação'],
    isFounder: true,
    roleTitle: 'Co-Fundador & Engenheiro de Privacidade e Redes',
    keyFingerprint: 'B18C:330F:D721:A855:40EC:66F2',
    completedExchanges: 52,
    ecoMeritPoints: 890,
    joinedDate: 'Fevereiro 2025',
  },
];

// Active Current User (Liron Kilson as shown in user's active session screenshot)
export const CURRENT_USER: UserNeighbor = {
  id: 'user-liron',
  name: 'Liron Kilson',
  firstName: 'Liron',
  middleName: 'Kilson',
  lastName: 'Manuel',
  phone: '+244 940 583 598',
  avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&auto=format&fit=crop&q=80',
  neighborhood: 'Bairro Central, Cacuso',
  reputationScore: 99,
  vouchesCount: 138,
  badges: ['Criador Oficial', 'Criptografia & Privacidade', 'Modo Profissional', 'Nó de Validação'],
  isFounder: true,
  roleTitle: 'Co-Fundador & Engenheiro de Privacidade e Redes',
  keyFingerprint: 'B18C:330F:D721:A855:40EC:66F2',
  completedExchanges: 52,
  ecoMeritPoints: 890,
  joinedDate: 'Fevereiro 2025',
  isProfessionalMode: true,
  followersCount: 18450,
  followingCount: 320,
};

export const NEIGHBORS: UserNeighbor[] = [
  ...FOUNDERS,
  CURRENT_USER,
  {
    id: 'user-esperanca',
    name: 'Esperança Nzola',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=200&auto=format&fit=crop&q=80',
    neighborhood: 'Bairro Capanda, Cacuso',
    reputationScore: 97,
    vouchesCount: 64,
    badges: ['Professora Comunitária', 'Banco de Tempo', 'Guardiã Verde'],
    keyFingerprint: '8E12:11AC:55FD:2291:88B1:012C',
    completedExchanges: 31,
    ecoMeritPoints: 510,
    joinedDate: 'Fevereiro 2025',
  },
  {
    id: 'user-antonio',
    name: 'Mestre António Kapenda',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=200&auto=format&fit=crop&q=80',
    neighborhood: 'Bairro da Estação, Cacuso',
    reputationScore: 95,
    vouchesCount: 47,
    badges: ['Carpinteiro Solidário', 'Mestre de Reparos', 'Selo de Confiança'],
    keyFingerprint: '99AC:D441:2B10:33E9:12CC:AA09',
    completedExchanges: 39,
    ecoMeritPoints: 420,
    joinedDate: 'Março 2025',
  },
  {
    id: 'user-tania',
    name: 'Tânia Sebastião',
    avatar: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=200&auto=format&fit=crop&q=80',
    neighborhood: 'Bairro Terra Nova, Cacuso',
    reputationScore: 92,
    vouchesCount: 22,
    badges: ['Agricultora Familiar', 'Cooperativa Mel de Cacuso', 'Eco-Defensora'],
    keyFingerprint: '3C19:F20A:7741:D910:CC44:66E1',
    completedExchanges: 22,
    ecoMeritPoints: 610,
    joinedDate: 'Março 2025',
  },
  {
    id: 'user-francisco',
    name: 'Francisco Bumba',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=200&auto=format&fit=crop&q=80',
    neighborhood: 'Bairro Muquixe / Cacuso',
    reputationScore: 98,
    vouchesCount: 54,
    badges: ['Viajante Comunitário', 'Amigo Leal'],
    keyFingerprint: '7A81:22BC:4410:EE89',
    completedExchanges: 28,
    ecoMeritPoints: 370,
    joinedDate: 'Fevereiro 2025',
  },
  {
    id: 'user-naice',
    name: 'Naice Reservado',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&auto=format&fit=crop&q=80',
    neighborhood: 'Bairro Central, Cacuso',
    reputationScore: 95,
    vouchesCount: 42,
    badges: ['Conectador Social', 'Música & Beat'],
    keyFingerprint: '9920:112A:BBD8:331C',
    completedExchanges: 19,
    ecoMeritPoints: 290,
    joinedDate: 'Março 2025',
  },
];

export const INITIAL_POSTS: Post[] = [
  {
    id: 'post-francisco-bumba',
    author: {
      id: 'user-francisco',
      name: 'Francisco Bumba',
      avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=200&auto=format&fit=crop&q=80',
      neighborhood: 'Bairro Muquixe / Cacuso',
      reputationScore: 98,
      vouchesCount: 54,
      badges: ['Viajante Comunitário'],
      keyFingerprint: '7A81:22BC:4410:EE89',
      completedExchanges: 28,
      ecoMeritPoints: 370,
      joinedDate: 'Fevereiro 2025',
    },
    neighborhood: 'Município de Muquixe, Cacuso',
    content: 'O meu dia a dia de ontem, no Município de Muquixe, foi mais ou menos assim: acompanhar esta jovem que, supostamente, também é minha família 😂😂😂 até ao Município de Muquixe, para realizar uma prova de admissão do concurso público.\n\nFoi muito divertido, porque parecia ser o mesmo solo que eu já tinha pisado antes na infância com os mais velhos. A energia da nossa terra nunca desilude! ❤️🇦🇴',
    timestamp: 'Ontem às 18:42',
    category: 'geral',
    likesCount: 57,
    hasLiked: false,
    tags: ['#Muquixe', '#Cacuso', '#Familia', '#Angola'],
    imageUrl: 'https://images.unsplash.com/photo-1528740561666-dc2479dc08ab?w=1000&auto=format&fit=crop&q=80',
    e2eeEncryptedFlag: false,
    comments: [
      {
        id: 'c-fb-1',
        author: FOUNDERS[1], // Liron Kilson
        content: 'Grande homem Francisco! Que tudo corra bem no concurso com a jovem da família! 👏',
        timestamp: 'Ontem às 19:10',
      },
      {
        id: 'c-fb-2',
        author: NEIGHBORS[3], // Esperança
        content: 'Muquixe é terra de gente boa e muito trabalhadora. Sucesso!',
        timestamp: 'Ontem às 19:45',
      },
    ],
  },
  {
    id: 'post-naice-reservado',
    author: {
      id: 'user-naice',
      name: 'Naice Reservado',
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&auto=format&fit=crop&q=80',
      neighborhood: 'Bairro Central, Cacuso',
      reputationScore: 95,
      vouchesCount: 42,
      badges: ['Conectador Social'],
      keyFingerprint: '9920:112A:BBD8:331C',
      completedExchanges: 19,
      ecoMeritPoints: 290,
      joinedDate: 'Março 2025',
    },
    neighborhood: 'Bairro Central, Cacuso',
    content: 'Tornou-se amigo/a de Reservado Memer II e 41 outras pessoas. 114 amigos em comum, incluindo New Star Fhamosinho e Girepro Beat. A família e a rede cultural continuam a crescer forte em Cacuso e Viana! 🤝🎶',
    timestamp: 'Há 5 horas',
    category: 'geral',
    likesCount: 84,
    hasLiked: true,
    tags: ['#AmigosDeVerdade', '#CacusoConectado', '#Kuduro'],
    imageUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=1000&auto=format&fit=crop&q=80',
    e2eeEncryptedFlag: false,
    comments: [
      {
        id: 'c-nr-1',
        author: FOUNDERS[0],
        content: 'Parabéns pela união! Conectar vizinhos sem algoritmos predatórios é a nossa meta.',
        timestamp: 'Há 3 horas',
      },
    ],
  },
  {
    id: 'post-1',
    author: FOUNDERS[0], // Jelson Pereira Manuel
    neighborhood: 'Bairro Central, Cacuso',
    content: '🎉 Bem-vindos ao Cacuso Online! Criado por mim e pelo Liron Kilson com uma missão clara: provar que a nossa comunidade não precisa de algoritmos opressivos de grandes corporações para prosperar. Aqui não há vigilância, não há venda de dados e o feed é 100% cronológico. Cada vizinho tem voz, os serviços são trocados com dignidade e cuidamos do nosso meio ambiente juntos!',
    timestamp: 'Há 25 minutos',
    category: 'aviso',
    likesCount: 38,
    hasLiked: true,
    tags: ['#InovacaoSocial', '#CacusoUnido', '#PrivacidadeGarantida'],
    imageUrl: 'https://images.unsplash.com/photo-1577495508048-b635879837f1?w=800&auto=format&fit=crop&q=80',
    e2eeEncryptedFlag: false,
    comments: [
      {
        id: 'c-1',
        author: NEIGHBORS[3], // Esperança Nzola
        content: 'Excelente iniciativa Jelson e Liron! Já comecei a disponibilizar reforço de matemática para as crianças sem custo no fórum.',
        timestamp: 'Há 18 minutos',
      },
      {
        id: 'c-2',
        author: FOUNDERS[1], // Liron Kilson
        content: 'É isso mesmo, Esperança! A segurança criptográfica garante que ninguém fora da vizinhança intromete-se nos nossos assuntos. O Cacuso é nosso!',
        timestamp: 'Há 12 minutos',
      },
    ],
  },
  {
    id: 'post-2',
    author: FOUNDERS[1], // Liron Kilson
    neighborhood: 'Bairro Central, Cacuso',
    content: '🔐 Transparência Criptográfica: Todas as mensagens diretas e propostas de transação no Cacuso Online utilizam chaves ponta-a-ponta. Nem os servidores, nem anunciantes, nem governos têm acesso ao conteúdo dos seus chats. A reputação é calculada de forma descentralizada por quem realmente vive no bairro.',
    timestamp: 'Há 1 hora',
    category: 'geral',
    likesCount: 29,
    hasLiked: false,
    tags: ['#CriptografiaE2EE', '#SoberaniaDigital', '#SegurançaDeVerdade'],
    comments: [
      {
        id: 'c-3',
        author: NEIGHBORS[4], // Mestre António
        content: 'Finalmente uma ferramenta limpa, sem anúncios a piscar nem mentiras no feed!',
        timestamp: 'Há 45 minutos',
      },
    ],
  },
  {
    id: 'post-3',
    author: NEIGHBORS[5], // Tânia Sebastião
    neighborhood: 'Bairro Terra Nova, Cacuso',
    content: '🌿 Mutirão de Limpeza & Coleta Seletiva no sábado! Vamos recolher plásticos ao longo da estrada principal e encaminhar tudo para o Ecoponto 02 (Quizenga). Cada participante receberá 50 Eco-Pontos no perfil e composto orgânico para hortas!',
    timestamp: 'Há 2 horas',
    category: 'sustentabilidade',
    likesCount: 44,
    hasLiked: true,
    tags: ['#EcoCacuso', '#LimpezaComunitaria', '#Sustentabilidade'],
    imageUrl: 'https://images.unsplash.com/photo-1618477461853-cf6ed80faba5?w=800&auto=format&fit=crop&q=80',
    comments: [],
  },
  {
    id: 'post-4',
    author: NEIGHBORS[4], // Mestre António Kapenda
    neighborhood: 'Bairro da Estação, Cacuso',
    content: '🔨 Reparei hoje sem cobrar nada as carteiras da escolinha primária do bairro com ajuda do banco de tempo comunitário. Em troca, o irmão Pedro ajudou-me a transportar pranchas de madeira. A economia colaborativa funciona quando há respeito mútuo!',
    timestamp: 'Há 3 horas',
    category: 'ajuda',
    likesCount: 52,
    hasLiked: false,
    tags: ['#BancoDeTempo', '#SemCusto', '#Solidariedade'],
    comments: [],
  },
];

export const INITIAL_SERVICE_SWAPS: ServiceSwap[] = [
  {
    id: 'srv-1',
    title: 'Aulas de Reforço de Matemática e Leitura para Crianças',
    type: 'oferta',
    category: 'educacao',
    description: 'Disponibilizo 2 horas semanais para reforço escolar de ensino fundamental. Não cobro dinheiro; aceito mudas para jardim ou auxílio com poda simples.',
    compensation: 'Sem custo monetário - Troca por ajuda na horta / Banco de Tempo',
    provider: NEIGHBORS[3], // Esperança Nzola
    neighborhood: 'Bairro Capanda',
    status: 'aberto',
    createdAt: 'Hoje às 09:30',
    interestedCount: 5,
  },
  {
    id: 'srv-2',
    title: 'Reparação de Fechaduras e Pequenos Móveis de Madeira',
    type: 'oferta',
    category: 'reparos',
    description: 'Posso consertar portas emperradas, bancos quebrados e pequenos reparos caseiros para os vizinhos do bairro.',
    compensation: 'Sem custo monetário - Aceito partilha de ferramentas ou 1 hora de banco de tempo',
    provider: NEIGHBORS[4], // Mestre António
    neighborhood: 'Bairro da Estação',
    status: 'aberto',
    createdAt: 'Hoje às 11:15',
    interestedCount: 3,
  },
  {
    id: 'srv-3',
    title: 'Preciso de Ajuda para Instalação de Painel Solar Simples',
    type: 'pedido',
    category: 'tecnologia',
    description: 'Tenho um kit solar de 150W para iluminação de emergência e preciso de orientação de um vizinho eletricista para conectar o inversor com segurança.',
    compensation: 'Ofereço 5kg de farinha de mandioca pura artesanal + assistência no que precisarem',
    provider: NEIGHBORS[5], // Tânia Sebastião
    neighborhood: 'Bairro Terra Nova',
    status: 'aberto',
    createdAt: 'Ontem às 16:40',
    interestedCount: 4,
  },
  {
    id: 'srv-4',
    title: 'Empréstimo de Bomba Manual de Irrigação & Pulverizador',
    type: 'oferta',
    category: 'agricultura',
    description: 'Equipamento em perfeito estado para quem estiver semeando milho ou hortaliças nesta época.',
    compensation: 'Sem custo monetário - Devolver limpo e partilhar sementes crioulas',
    provider: FOUNDERS[0], // Jelson Pereira Manuel
    neighborhood: 'Bairro Central',
    status: 'aberto',
    createdAt: 'Ontem às 14:00',
    interestedCount: 6,
  },
  {
    id: 'srv-5',
    title: 'Carona Compartilhada Semanal Cacuso <-> Malanje Centro',
    type: 'oferta',
    category: 'transporte',
    description: 'Vou às terças e sextas cedo ao centro de Malanje para tratar de assuntos e tenho 2 lugares livres na carrinha para vizinhos.',
    compensation: 'Sem cobrança de frete - Solidariedade comunitária',
    provider: CURRENT_USER,
    neighborhood: 'Bairro Quizenga',
    status: 'aberto',
    createdAt: 'Há 2 dias',
    interestedCount: 2,
  },
];

export const INITIAL_MARKETPLACE_ITEMS: MarketplaceItem[] = [
  {
    id: 'mkt-1',
    title: 'Mandioca Amarela e Ginguba Torrada Fresca de Cacuso',
    price: '1.200 Kz / Saco ou Troca',
    category: 'terra_agricultura',
    description: 'Colhida ontem na lavra familiar em Quizenga. Produto 100% orgânico, sem químicos. Aberto a trocas por outros alimentos.',
    seller: NEIGHBORS[5], // Tânia
    neighborhood: 'Bairro Quizenga',
    condition: 'Colheita Fresca',
    isTradeOrFairPrice: true,
    imageUrl: 'https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?w=600&auto=format&fit=crop&q=80',
    createdAt: 'Há 3 horas',
    status: 'disponivel',
  },
  {
    id: 'mkt-2',
    title: 'Mel Puro Silvestre das Florestas de Cacuso (Garrafa 1L)',
    price: '3.000 Kz (Preço Justo)',
    category: 'alimentos',
    description: 'Mel artesanal não pasteurizado, extraído de forma sustentável preservando os enxames nativos.',
    seller: FOUNDERS[1], // Liron Kilson
    neighborhood: 'Bairro Central',
    condition: 'Novo',
    isTradeOrFairPrice: true,
    imageUrl: 'https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=600&auto=format&fit=crop&q=80',
    createdAt: 'Há 5 horas',
    status: 'disponivel',
  },
  {
    id: 'mkt-3',
    title: 'Cestos de Vime Trançados à Mão Tradicionais',
    price: '2.500 Kz ou Troca por Tecidos',
    category: 'artesanato',
    description: 'Feitos com fibras locais e tingimento natural. Ideais para colheita, compras ou decoração sustentável.',
    seller: NEIGHBORS[3], // Esperança
    neighborhood: 'Bairro Capanda',
    condition: 'Novo',
    isTradeOrFairPrice: true,
    imageUrl: 'https://images.unsplash.com/photo-1544816155-12df9643f363?w=600&auto=format&fit=crop&q=80',
    createdAt: 'Ontem',
    status: 'disponivel',
  },
  {
    id: 'mkt-4',
    title: 'Kit de Enxadas e Rastelos para Trabalho Coletivo',
    price: 'Doação / Empréstimo Coletivo',
    category: 'ferramentas',
    description: 'Doado para o banco de ferramentas do bairro. Quem precisar pode retirar no ponto de apoio e devolver em 3 dias.',
    seller: NEIGHBORS[4], // Mestre António
    neighborhood: 'Bairro da Estação',
    condition: 'Usado Bom',
    isTradeOrFairPrice: true,
    imageUrl: 'https://images.unsplash.com/photo-1589923188900-85dae523342b?w=600&auto=format&fit=crop&q=80',
    createdAt: 'Há 2 dias',
    status: 'disponivel',
  },
];

export const INITIAL_ECO_POINTS: EcoWastePoint[] = [
  {
    id: 'eco-pt-1',
    name: 'Ecoponto Central Cacuso',
    location: 'Largo da Feira Municipal, Cacuso',
    neighborhood: 'Bairro Central',
    acceptedTypes: ['plastico', 'vidro', 'metal', 'eletronico'],
    capacityPercentage: 45,
    coordinator: 'Jelson Pereira Manuel',
    operatingHours: 'Seg - Sáb: 07:30 às 17:00',
  },
  {
    id: 'eco-pt-2',
    name: 'Ponto Verde Quizenga & Compostagem Coletiva',
    location: 'Rua das Mangueiras, junto ao Posto Comunitário',
    neighborhood: 'Bairro Quizenga',
    acceptedTypes: ['organico', 'plastico'],
    capacityPercentage: 68,
    coordinator: 'Tânia Sebastião',
    operatingHours: 'Todos os dias: 06:00 às 18:30',
  },
  {
    id: 'eco-pt-3',
    name: 'Ecoponto Estação Ferroviária',
    location: 'Antigo Pátio da Estação, Cacuso',
    neighborhood: 'Bairro da Estação',
    acceptedTypes: ['metal', 'vidro', 'plastico'],
    capacityPercentage: 30,
    coordinator: 'Mestre António Kapenda',
    operatingHours: 'Seg - Sex: 08:00 às 16:00',
  },
  {
    id: 'eco-pt-4',
    name: 'Ecoponto Escolar Capanda',
    location: 'Entrada da Escola Secundária Capanda',
    neighborhood: 'Bairro Capanda',
    acceptedTypes: ['plastico', 'organico'],
    capacityPercentage: 55,
    coordinator: 'Esperança Nzola',
    operatingHours: 'Seg - Sex: 07:00 às 18:00',
  },
];

export const INITIAL_ECO_REPORTS: EcoWasteReport[] = [
  {
    id: 'rep-1',
    title: 'Triagem de 120kg de Plásticos no Bairro Central',
    type: 'descarte_correto',
    description: 'Plásticos compactados e destinados à cooperativa de reciclagem provincial.',
    reportedBy: FOUNDERS[1], // Liron Kilson
    neighborhood: 'Bairro Central',
    kgCollected: 120,
    ecoPointsAwarded: 120,
    date: 'Hoje, 10:45',
    status: 'meta_alcancada',
  },
  {
    id: 'rep-2',
    title: 'Compostagem Orgânica de Feirantes em Quizenga',
    type: 'compostagem_coletiva',
    description: 'Resíduos de cascas de mandioca, frutas e folhas convertidos em adubo rico para 15 famílias agricultoras.',
    reportedBy: NEIGHBORS[5], // Tânia
    neighborhood: 'Bairro Quizenga',
    kgCollected: 340,
    ecoPointsAwarded: 180,
    date: 'Ontem',
    status: 'verificado_vizinhos',
  },
  {
    id: 'rep-3',
    title: 'Mutirão de Limpeza da Vala de Drenagem da Estação',
    type: 'mutirao_limpeza',
    description: '28 vizinhos reunidos para desobstrução e remoção de garrafas pet e entulho antes da época de chuvas.',
    reportedBy: NEIGHBORS[4], // António
    neighborhood: 'Bairro da Estação',
    kgCollected: 450,
    ecoPointsAwarded: 250,
    date: 'Há 3 dias',
    status: 'meta_alcancada',
  },
];

export const INITIAL_EVENTS: CommunityEvent[] = [
  {
    id: 'ev-1',
    title: '1º Fórum de Economia Circular e Troca Sem Custo de Cacuso',
    description: 'Encontro com os fundadores Jelson Pereira Manuel e Liron Kilson para planejar expansão de hortas e segurança digital local.',
    date: 'Sábado, 15 de Março',
    time: '09:00 - 12:30',
    location: 'Centro Comunitário de Cacuso',
    neighborhood: 'Bairro Central',
    organizer: FOUNDERS[0],
    category: 'assembleia',
    attendeesCount: 74,
    isAttending: true,
  },
  {
    id: 'ev-2',
    title: 'Grande Feira da Mandioca e Mel Artesanal com Trocas Diretas',
    description: 'Traga excedentes da sua lavra ou itens artesanais para trocar sem intermediação financeira.',
    date: 'Domingo, 23 de Março',
    time: '08:00 - 15:00',
    location: 'Largo da Estação de Cacuso',
    neighborhood: 'Bairro da Estação',
    organizer: NEIGHBORS[5],
    category: 'feira_troca',
    attendeesCount: 118,
    isAttending: false,
  },
  {
    id: 'ev-3',
    title: 'Oficina Prática de Compostagem Caseira & Plantio de Mudas',
    description: 'Aprenda a transformar o lixo orgânico da sua cozinha no melhor adubo natural da região.',
    date: 'Sábado, 29 de Março',
    time: '14:30 - 17:00',
    location: 'Horta Comunitária Quizenga',
    neighborhood: 'Bairro Quizenga',
    organizer: NEIGHBORS[3],
    category: 'oficina',
    attendeesCount: 42,
    isAttending: true,
  },
];

export const INITIAL_VOUCHES: ReputationVouch[] = [
  {
    id: 'vouch-1',
    fromNeighbor: FOUNDERS[0],
    toNeighborId: 'user-self',
    category: 'troca_honesta',
    comment: 'Vizinho Manuel cumpriu pontualmente o empréstimo da carrinha solidária com total zelo.',
    timestamp: 'Ontem',
    signatureHash: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
  },
  {
    id: 'vouch-2',
    fromNeighbor: NEIGHBORS[3],
    toNeighborId: 'user-self',
    category: 'guardiao_ambiental',
    comment: 'Apoio exemplar na manutenção do ecoponto e descarte consciente de pilhas e baterias.',
    timestamp: 'Há 3 dias',
    signatureHash: '8b7df143d91c716ecfa5fc1730022f6b421b05cedee8fd52b1fc65a96030ad52',
  },
  {
    id: 'vouch-3',
    fromNeighbor: FOUNDERS[1],
    toNeighborId: 'user-antonio',
    category: 'confianca_geral',
    comment: 'Mestre António é pilar da integridade de Cacuso, mais de 30 serviços prestados voluntariamente.',
    timestamp: 'Há 5 dias',
    signatureHash: '4355a46b19d348dc2f57c046f8ef63d4538ebb936000f3c9ee954a27460dd865',
  },
];

export const INITIAL_MESSAGES: DirectMessage[] = [
  {
    id: 'msg-1',
    senderId: 'founder-jelson',
    receiverId: 'user-self',
    encryptedPayload: 'AES-GCM:Iv78aQ==:8F91B0CA391D...',
    plainText: 'Olá vizinho Manuel! Como está a funcionar a nova versão do Cacuso Online no teu bairro? Criamos tudo sem algoritmos para vos dar total liberdade.',
    timestamp: '14:20',
    isMine: false,
    verifiedE2EE: true,
  },
  {
    id: 'msg-2',
    senderId: 'user-self',
    receiverId: 'founder-jelson',
    encryptedPayload: 'AES-GCM:28aFkL==:CD14E299A102...',
    plainText: 'Saudações Jelson! Está excelente. A vizinhança adorou a transparência e a facilidade de trocar ferramentas sem burocracia.',
    timestamp: '14:22',
    isMine: true,
    verifiedE2EE: true,
  },
  {
    id: 'msg-3',
    senderId: 'founder-jelson',
    receiverId: 'user-self',
    encryptedPayload: 'AES-GCM:K91mPx==:17AB99D430C1...',
    plainText: 'Excelente! O Liron também reforçou a criptografia ponta a ponta para que nenhuma conversa saia do vosso dispositivo.',
    timestamp: '14:25',
    isMine: false,
    verifiedE2EE: true,
  },
];

export const FACEBOOK_STORIES: UserStory[] = [
  {
    id: 'story-adelaide',
    authorName: 'Adelaide Golome',
    authorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80',
    mediaUrl: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=800&auto=format&fit=crop&q=80',
    mediaType: 'image',
    timestamp: 'Há 1 hora',
    caption: 'Dia de ensaio e muita boa energia em Cacuso! 🇦🇴✨',
    isViewed: false,
  },
  {
    id: 'story-saf',
    authorName: 'Éu Saf Mugabh',
    authorAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&auto=format&fit=crop&q=80',
    mediaUrl: 'https://images.unsplash.com/photo-1506157786151-b8491531f063?w=800&auto=format&fit=crop&q=80',
    mediaType: 'image',
    timestamp: 'Há 2 horas',
    caption: 'Na estrada para o estúdio com a tropa.',
    isViewed: false,
  },
  {
    id: 'story-ady',
    authorName: 'Ady West O Flownomenal',
    authorAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&auto=format&fit=crop&q=80',
    mediaUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=800&auto=format&fit=crop&q=80',
    mediaType: 'image',
    timestamp: 'Há 3 horas',
    caption: 'Gravação da nova faixa pesada. Aguardem!',
    isViewed: false,
  },
  {
    id: 'story-colua',
    authorName: 'Cólua Tremura',
    authorAvatar: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=200&auto=format&fit=crop&q=80',
    mediaUrl: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800&auto=format&fit=crop&q=80',
    mediaType: 'image',
    timestamp: 'Há 4 horas',
    caption: 'Reservas e agenda abertas: 940 583 598',
    isViewed: false,
  },
  {
    id: 'story-pedro',
    authorName: 'PEDRO JD',
    authorAvatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=200&auto=format&fit=crop&q=80',
    mediaUrl: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=800&auto=format&fit=crop&q=80',
    mediaType: 'image',
    timestamp: 'Há 5 horas',
    caption: 'Ao vivo em Cacuso com som de raiz.',
    isViewed: false,
  },
  {
    id: 'story-john',
    authorName: 'John Major Antoine',
    authorAvatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=200&auto=format&fit=crop&q=80',
    mediaUrl: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=800&auto=format&fit=crop&q=80',
    mediaType: 'image',
    timestamp: 'Há 6 horas',
    caption: 'Reunião de negócios e parcerias.',
    isViewed: true,
  },
  {
    id: 'story-nadia',
    authorName: 'Nádia Elias',
    authorAvatar: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=200&auto=format&fit=crop&q=80',
    mediaUrl: 'https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=800&auto=format&fit=crop&q=80',
    mediaType: 'image',
    timestamp: 'Há 7 horas',
    caption: 'A natureza da nossa terra é incomparável. ❤️',
    isViewed: true,
  },
];

export const FACEBOOK_REELS: FacebookReel[] = [
  {
    id: 'reel-1',
    author: {
      id: 'author-liron',
      name: 'Liron Kilson',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&auto=format&fit=crop&q=80',
      neighborhood: 'Bairro Central, Cacuso',
      reputationScore: 99,
      vouchesCount: 138,
      badges: ['Criador Oficial', 'DJ & Produtor', 'Modo Profissional'],
      keyFingerprint: 'B18C:330F:D721:A855:40EC:66F2',
      completedExchanges: 52,
      ecoMeritPoints: 890,
      joinedDate: 'Fevereiro 2025',
    },
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-young-man-dancing-in-a-studio-41131-large.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=800&auto=format&fit=crop&q=80',
    caption: 'Batida nova de Kuduro gravada em Cacuso! 🔥 Quem curtiu comenta aí qual bairro tem mais swing. #Kuduro #CacusoMusik #AngolaVibes #RitmoNacional',
    audioTrack: 'Liron Kilson • Som Original - Batida Cacuso 2026',
    likesCount: 24810,
    commentsCount: 1420,
    sharesCount: 3890,
    viewsCount: 145000,
    hasLiked: true,
    tags: ['#Kuduro', '#CacusoMusik', '#AngolaVibes', '#Malanje'],
    commentsList: [
      { id: 'rc-1', author: 'Adelaide Golome', avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80', text: 'Essa batida está a bater muito forte Liron! Parabéns mano! 🔥🇦🇴', time: 'Há 15 min' },
      { id: 'rc-2', author: 'Éu Saf Mugabh', avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop&q=80', text: 'Viana já está a tocar esse som em todo o canto! 👏', time: 'Há 32 min' },
      { id: 'rc-3', author: 'Jelson Pereira Manuel', avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80', text: 'Cultura de Cacuso no topo do país!', time: 'Há 1 hora' },
    ],
  },
  {
    id: 'reel-2',
    author: {
      id: 'author-adelaide',
      name: 'Adelaide Golome',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80',
      neighborhood: 'Bairro Quizenga, Cacuso',
      reputationScore: 96,
      vouchesCount: 45,
      badges: ['Criadora de Conteúdo', 'Dança Angolana'],
      keyFingerprint: '44F1:99B2:C010:77A2',
      completedExchanges: 19,
      ecoMeritPoints: 310,
      joinedDate: 'Março 2025',
    },
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-group-of-friends-dancing-happily-in-a-party-41618-large.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1547153760-18fc86324498?w=800&auto=format&fit=crop&q=80',
    caption: 'Passo novo para o final de semana! Quem consegue fazer esse toque em casa? Mostrem o talento de vocês nos comentários! 💃🏾🕺🏾 #DancaAngolana #Semba #Kuduro',
    audioTrack: 'Adelaide Golome • Toque Tradicional Cacuso',
    likesCount: 18950,
    commentsCount: 940,
    sharesCount: 2150,
    viewsCount: 98000,
    hasLiked: false,
    tags: ['#DancaAngolana', '#Kuduro', '#Alegria', '#Cacuso'],
    commentsList: [
      { id: 'rc-4', author: 'Nádia Elias', avatar: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=100&auto=format&fit=crop&q=80', text: 'Que ginga linda! Vou tentar aprender hoje mesmo haha', time: 'Há 40 min' },
      { id: 'rc-5', author: 'Cólua Tremura', avatar: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=100&auto=format&fit=crop&q=80', text: 'Top top top, Cacuso tem talento de sobra!', time: 'Há 1 hora' },
    ],
  },
  {
    id: 'reel-3',
    author: {
      id: 'author-pedro',
      name: 'PEDRO JD',
      avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=200&auto=format&fit=crop&q=80',
      neighborhood: 'Bairro da Estação, Cacuso',
      reputationScore: 94,
      vouchesCount: 38,
      badges: ['Comediante', 'Voz do Bairro'],
      keyFingerprint: '99AC:88F1:314B:55AA',
      completedExchanges: 12,
      ecoMeritPoints: 240,
      joinedDate: 'Março 2025',
    },
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-african-boy-smiling-and-looking-at-the-camera-40748-large.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=800&auto=format&fit=crop&q=80',
    caption: 'Quando você diz que vai só ali na feira de Cacuso comprar ginguba e volta 4 horas depois conversando com todos os vizinhos 😂😂😂 É ou não é verdade gente?! #HumorAngolano #VidaEmCacuso',
    audioTrack: 'PEDRO JD • Risadas e Resenha de Cacuso',
    likesCount: 31200,
    commentsCount: 2890,
    sharesCount: 5410,
    viewsCount: 220000,
    hasLiked: true,
    tags: ['#HumorAngolano', '#Cacuso', '#Resenha', '#Angola'],
    commentsList: [
      { id: 'rc-6', author: 'Francisco Bumba', avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=100&auto=format&fit=crop&q=80', text: 'Manda mais mano! Em Muquixe acontece igualzinho kkkk', time: 'Há 25 min' },
      { id: 'rc-7', author: 'Liron Kilson', avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop&q=80', text: 'Aqui em Cacuso é assim mesmo, vizinhança é família!', time: 'Há 50 min' },
    ],
  },
];

export const COMMUNITY_GROUPS: CommunityGroup[] = [
  {
    id: 'grp-kuduro',
    name: 'Kuduro & Ritmos Angolanos (Cacuso & Luanda)',
    description: 'Comunidade de produtores, DJs, dançarinos e apreciadores de Kuduro, Afrohouse e Semba. Divulgação de novidades, lançamentos e eventos em Malanje e Luanda.',
    coverImage: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=800&auto=format&fit=crop&q=80',
    memberCount: 45200,
    privacy: 'publico',
    category: 'Música & Dança',
    isMember: true,
    location: 'Cacuso & Luanda',
  },
  {
    id: 'grp-viana',
    name: 'VENDA DE MATERIAIS DE ESTUDIO EM VIANA',
    description: 'Compra, venda e troca de equipamentos de estúdio, microfones, placas de som, monitores de áudio, sintetizadores e cabos em Viana e Cacuso.',
    coverImage: 'https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?w=800&auto=format&fit=crop&q=80',
    memberCount: 28400,
    privacy: 'publico',
    category: 'Classificados & Áudio',
    isMember: true,
    location: 'Viana, Luanda & Cacuso',
  },
  {
    id: 'grp-negocios',
    name: 'Cacuso Negócios, Emprego e Oportunidades',
    description: 'Rede de empresários locais, prestadores de serviços, vagas de emprego e parcerias comerciais no Município de Cacuso e Província de Malanje.',
    coverImage: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&auto=format&fit=crop&q=80',
    memberCount: 19800,
    privacy: 'publico',
    category: 'Negócios & Carreira',
    isMember: true,
    location: 'Cacuso, Malanje',
  },
  {
    id: 'grp-agro',
    name: 'Agricultores e Cooperativas da Região',
    description: 'Partilha de técnicas sustentáveis de plantio, feiras de sementes, escoamento de mandioca e mel de abelha silvestre de Cacuso.',
    coverImage: 'https://images.unsplash.com/photo-1500937386664-56d1dfef3854?w=800&auto=format&fit=crop&q=80',
    memberCount: 14200,
    privacy: 'publico',
    category: 'Agricultura & Sustentabilidade',
    isMember: false,
    location: 'Cacuso & Capanda',
  },
];

export const FACEBOOK_PAGES: FacebookPage[] = [
  {
    id: 'page-cacuso-musik',
    name: 'Cacuso Musik',
    category: 'Gravadora & Produtora Musical',
    bio: 'Produtora oficial e selo discográfico independente com base em Cacuso. Elevando os talentos do Kuduro, Afrohouse e Kizomba.',
    avatar: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=200&auto=format&fit=crop&q=80',
    coverImage: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=1000&auto=format&fit=crop&q=80',
    followersCount: 38400,
    likesCount: 32100,
    phone: '+244 940 583 598',
    location: 'Bairro Central, Cacuso, Angola',
    isOfficial: true,
  },
  {
    id: 'page-sua-excelencia',
    name: 'Sua Excelência',
    category: 'Marca & Personalidade Pública',
    bio: 'Página oficial de projetos culturais, inovação comunitária e iniciativas de desenvolvimento para a juventude angolana.',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&auto=format&fit=crop&q=80',
    coverImage: 'https://images.unsplash.com/photo-1506157786151-b8491531f063?w=1000&auto=format&fit=crop&q=80',
    followersCount: 27900,
    likesCount: 24500,
    phone: '+244 931 456 041',
    location: 'Cacuso & Luanda, Angola',
    isOfficial: true,
  },
  {
    id: 'page-estudio-viana',
    name: 'VENDA DE MATERIAIS DE ESTUDIO EM VIANA',
    category: 'Loja de Instrumentos & Áudio',
    bio: 'Equipamentos profissionais de gravação para estúdios musicais em Angola. Entregas em Luanda, Malanje e Cacuso.',
    avatar: 'https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?w=200&auto=format&fit=crop&q=80',
    coverImage: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=1000&auto=format&fit=crop&q=80',
    followersCount: 15400,
    likesCount: 13900,
    phone: '+244 923 112 233',
    location: 'Viana, Luanda',
    isOfficial: false,
  },
  {
    id: 'page-kuduro-com',
    name: 'Kuduro.com',
    category: 'Comunidade de Entretenimento',
    bio: 'O portal número 1 do Kuduro mundial. Notícias, vídeos, entrevistas e lançamentos exclusivos dos maiores artistas.',
    avatar: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=200&auto=format&fit=crop&q=80',
    coverImage: 'https://images.unsplash.com/photo-1547153760-18fc86324498?w=1000&auto=format&fit=crop&q=80',
    followersCount: 89000,
    likesCount: 81200,
    location: 'Luanda, Angola',
    isOfficial: true,
  },
];

export const FRIEND_REQUESTS: FriendRequest[] = [
  {
    id: 'req-gloria',
    name: 'Glória Miguel Mana Avó',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=200&auto=format&fit=crop&q=80',
    mutualFriendsCount: 7,
    mutualFriendsPreview: '7 amigos em comum',
    timestamp: 'Há 4 dias',
    status: 'pending',
  },
  {
    id: 'req-reservado',
    name: 'Reservado Memer II',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=200&auto=format&fit=crop&q=80',
    mutualFriendsCount: 29,
    mutualFriendsPreview: '29 amigos em comum',
    timestamp: 'Há 4 horas',
    status: 'pending',
  },
  {
    id: 'req-mateus',
    name: 'Mateus Pegado',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&auto=format&fit=crop&q=80',
    mutualFriendsCount: 11,
    mutualFriendsPreview: '11 amigos em comum',
    timestamp: 'Há 12 horas',
    status: 'pending',
  },
];

export const FACEBOOK_NOTIFICATIONS: FacebookNotification[] = [
  {
    id: 'notif-1',
    type: 'friend_request',
    senderName: 'Reservado Memer II',
    senderAvatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=100&auto=format&fit=crop&q=80',
    content: 'enviou-te um pedido de amizade.',
    timestamp: 'Há 4 horas',
    isRead: false,
  },
  {
    id: 'notif-2',
    type: 'reaction',
    senderName: 'Adelaide Golome',
    senderAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80',
    content: 'reagiu com ❤️ à tua publicação sobre a nova produção em Cacuso.',
    timestamp: 'Há 5 horas',
    isRead: false,
  },
  {
    id: 'notif-3',
    type: 'reel',
    senderName: 'PEDRO JD',
    senderAvatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=100&auto=format&fit=crop&q=80',
    content: 'publicou um novo Reel: "Quando você diz que vai só ali na feira...".',
    timestamp: 'Há 7 horas',
    isRead: true,
  },
  {
    id: 'notif-4',
    type: 'group',
    senderName: 'Kuduro & Ritmos Angolanos',
    senderAvatar: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=100&auto=format&fit=crop&q=80',
    content: 'há 12 novas publicações no grupo hoje.',
    timestamp: 'Há 1 dia',
    isRead: true,
  },
];

export const PROFESSIONAL_METRICS: ProfessionalMetrics = {
  reach: { value: 284520, percentChange: 18.4 },
  engagement: { value: 52840, percentChange: 24.1 },
  netFollowers: { value: 4120, percentChange: 12.7 },
  threeSecViews: { value: 198300, percentChange: 35.2 },
  earningsKz: 84500,
  starsCount: 3420,
  recentContentPerformance: [
    {
      id: 'perf-1',
      title: 'Batida nova de Kuduro gravada em Cacuso! 🔥',
      type: 'reel',
      publishedAt: 'Ontem às 19:40',
      impressions: 145000,
      interactions: 28700,
      shares: 3890,
    },
    {
      id: 'perf-2',
      title: '🔐 Transparência Criptográfica e Soberania Digital',
      type: 'post',
      publishedAt: 'Há 3 dias',
      impressions: 62400,
      interactions: 11200,
      shares: 1420,
    },
    {
      id: 'perf-3',
      title: 'Abertura do novo Estúdio Cacuso Musik com equipamentos de ponta',
      type: 'post',
      publishedAt: 'Há 5 dias',
      impressions: 89300,
      interactions: 16400,
      shares: 2180,
    },
  ],
};
